---
name: chrony
version: dev
slug: chrony
description: A local NTP (Network Time Protocol) server for cameras etc.
url: https://github.com/hassio-addons/addon-chrony
startup: system
arch:
  - aarch64
  - amd64
hassio_api: true
init: false
privileged:
  - SYS_TIME
ports:
  123/udp: 123
ports_description:
  123/udp: NTP; Network Time Protocol
options:
  set_system_clock: true
  ntp_pool: pool.ntp.org
  ntp_server: []
  pool_maxsources: 4
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  set_system_clock: bool
  ntp_pool: str?
  ntp_server:
    - str?
  pool_maxsources: int(1,16)
  mode: list(pool|server)?
